[theme]
base = "light"
primaryColor = "#0B6E58"
backgroundColor = "#F3F6F4"
secondaryBackgroundColor = "#E3F3EE"
textColor = "#10302B"
font = "sans serif"

[server]
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
